### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by mymxhdd** [chenxiaoyouyou/Bert-BiLSTM-CRF-pytorch#2]
在这一步报错
File "/data/Bert-BiLSTM-CRF-pytorch/model/bert_lstm_crf.py", line 47, in forward
    embeds, _ = self.word_embeds(sentence, attention_mask=attention_mask, output_all_encoded_layers=False)
TypeError: 'NoneType' object is not callable
请问是什么原因

**Comment by chenxiaoyouyou** [comment]
某一个函数调用是None

**Comment by zjcanjux** [comment]
> 在这一步报错
> File "/data/Bert-BiLSTM-CRF-pytorch/model/bert_lstm_crf.py", line 47, in forward
> embeds, _ = self.word_embeds(sentence, attention_mask=attention_mask, output_all_encoded_layers=False)
> TypeError: 'NoneType' object is not callable
> 请问是什么原因

请问你解决了么？

**Comment by zjcanjux** [comment]
> 某一个函数调用是None

这个代码你跑过么？我也遇到同样问题

**Comment by zjcanjux** [comment]
bert model路径不对

**Comment by ysgncss** [comment]
请问单字符标签怎么表示? 没有 S tag?
